name: playback_progress_bar
description: A progress bar widget to show or change the position of an audio or
  video stream.
version: 0.10.0
homepage: https://github.com/suragch/audio_video_progress_bar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter: null
